name: Move to column
on:
  issues: 
    types: [labeled]
    
    
jobs:
  move_cards:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: ${{ secrets.PAT }}
        project-url: https://github.com/philipstape/workshop-github-actions/projects/1
        column-name: "Waiting Test"
        label-name: "Waiting Test"
        columns-to-ignore: "Resolved"
    
