name: Move to Waiting Test
on:
  release: 
    types: [published]
    
jobs:
  move_cards:
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          comment-template: |
            Release {release_link} addresses this.
          label-template: "Waiting Test"
          skip-label: resolved
